/**
 * Content model for the HTML catalog. Generated by
 * scripts/python/build_catalog_content.py from the InDesign IDML source —
 * see docs/ADMIN.md for the update workflow.
 */

export interface CatalogImage {
  src: string;
  width: number;
  height: number;
  alt: string;
  /** gallery = product renders shown at the top; figure = charts/diagrams
   *  shown in the figures section with captions. */
  role: 'gallery' | 'figure';
  caption?: string;
}

export interface SpecRow {
  label: string;
  /** One value per model column. Trailing empty strings mean the first
   *  value spans all models (matches the print catalog's merged cells). */
  values: string[];
  note?: string;
}

export interface SpecTable {
  title: string;
  rows: SpecRow[];
}

export interface ProductVariant {
  title: string;
  description: string[];
  applications: string[];
}

export interface CatalogProduct {
  slug: string;
  category: string;
  group: string;
  name: string;
  models: string[];
  summary: string;
  description: string[];
  applications: string[];
  variants: ProductVariant[];
  specs: SpecTable[];
  images: CatalogImage[];
}

export interface CatalogCategory {
  slug: string;
  name: string;
  productLine: string;
  tagline: string;
  intro: string[];
  groups: string[];
}

export interface CatalogAbout {
  intro: string[];
  quote: { text: string; attribution: string };
  pillars: { title: string; text: string }[];
  productLines: { id: string; name: string; text: string }[];
  patents: string;
  patentsUrl: string;
}

export interface CatalogContent {
  edition: string;
  source: string;
  about: CatalogAbout;
  categories: CatalogCategory[];
  products: CatalogProduct[];
}
