import caseStudiesJson from './case-studies.json';

/**
 * Case studies — the 46 success stories from the success-stories catalog, one
 * page per story (Jul 2026; replaced the 21 WordPress-era studies — those 21
 * kept their slugs, so live URLs and the WP-era redirects in
 * src/lib/redirects.ts stayed valid).
 *
 * The JSON is GENERATED by scripts/python/build_case_studies.py from the
 * InDesign package in sources/success-stories/ + tags.csv (see docs/ADMIN.md).
 * Since Aug 2026 the prose is read from the IDML's PARAGRAPH STYLES rather
 * than recovered from the exported PDF's text layer, so the headline,
 * subtitle, story column and challenge/solution/results sidebar each come from
 * the style the designer applied instead of from line-length heuristics.
 * Slugs are FROZEN: redirects and indexed URLs depend on them.
 */

export interface CaseStudy {
  slug: string;
  /** 1-based page number in the success-stories flipbook PDF. */
  page: number;
  /** Un-branded SEO title (root template appends "| Petromac"). */
  title: string;
  /**
   * The story's standfirst, from the layout's `header-Gray txt` style — a
   * one-line summary sitting under the headline on 42 of the 46 pages. The
   * PDF-text pipeline swept this into the narrative, so it read as a stray
   * duplicate first sentence; it is a separate field since Aug 2026.
   */
  subtitle: string | null;
  metaDescription: string;
  country: string;
  region: string;
  year: number | null;
  wirelineCompany: string;
  /** Product line, e.g. "Wireline Express - FT", "Focus - CH". */
  device: string;
  categories: string[];
  challenge: string[];
  solution: string[];
  results: string[];
  /** Long-form narrative paragraphs from the story page. */
  narrative: string[];
  /** The published flipbook page — figures, logs and layout included. */
  image: { src: string; width: number; height: number };
  /**
   * The region world-map the printed page opens with — one of six shared
   * assets (exported once by extract_story_figures.py into figures/maps/),
   * with the story's region highlighted and labelled. Shown at the top of the
   * story sidebar; `region` carries the matching tags.csv area code.
   */
  regionMap: { src: string; width: number; height: number } | null;
  /**
   * The story's figures, in reading order, with the caption the layout gives
   * each one. The page used to render `image` (the whole published page) below
   * the extracted prose, which repeated every word of the story back as
   * pixels; these carry the part of the page the text can't.
   *
   * Built by scripts/python/extract_story_figures.py, which reads the figure
   * and caption geometry out of the InDesign IDML and renders each figure's
   * region from the export PDF. That replaced a pdfimages pass that could not
   * see vector artwork (pages 19, 20, 21, 30 and 34 shipped without their logs
   * and graphs) and split composited figures apart (pages 7, 9, 10 and 17).
   * `caption` is null where the layout gives the figure none.
   */
  figures: {
    src: string;
    width: number;
    height: number;
    caption: string | null;
  }[];
}

export const caseStudies = caseStudiesJson as CaseStudy[];

export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudies.find((cs) => cs.slug === slug);
}
