services:
  petromac:
    image: ghcr.io/klaratech/petromac:latest
    container_name: petromac
    env_file:
      - /opt/petromac/.env.prod
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
