import type { FlipbookManifest } from './types';
import type { FlipbookKey } from './constants';
import { FLIPBOOK_KEYS } from './constants';
// The manifest is a small committed build artifact, regenerated by
// `pnpm run data`. Importing it at build time removes a runtime fetch
// round-trip that used to gate the flipbook load. Only success-stories
// is an image flipbook now — the catalog moved to an in-browser pdf.js
// viewer (Jul 2026) and no longer has page images or a manifest.
import successStoriesManifest from '../../../public/flipbooks/success-stories/manifest.json';

const MANIFESTS: Partial<Record<FlipbookKey, FlipbookManifest>> = {
  [FLIPBOOK_KEYS.successStories]: successStoriesManifest as FlipbookManifest,
};

export function getFlipbookManifest(docKey: FlipbookKey): FlipbookManifest {
  const manifest = MANIFESTS[docKey];
  if (!manifest) {
    throw new Error(`No flipbook manifest for "${docKey}" (not an image flipbook)`);
  }
  return manifest;
}
