import type { FlipbookManifest } from './types';
import type { FlipbookKey } from './constants';
import { FLIPBOOK_KEYS } from './constants';
// The manifests are small committed build artifacts (~200 bytes each),
// regenerated by `pnpm run data`. Importing them at build time removes a
// runtime fetch round-trip that used to gate the entire flipbook load:
// nothing (page URLs, the page-flip chunk, the images) could start until
// manifest.json came back over the network.
import successStoriesManifest from '../../../public/flipbooks/success-stories/manifest.json';
import catalogManifest from '../../../public/flipbooks/catalog/manifest.json';

const MANIFESTS: Record<FlipbookKey, FlipbookManifest> = {
  [FLIPBOOK_KEYS.successStories]: successStoriesManifest as FlipbookManifest,
  [FLIPBOOK_KEYS.catalog]: catalogManifest as FlipbookManifest,
};

export function getFlipbookManifest(docKey: FlipbookKey): FlipbookManifest {
  return MANIFESTS[docKey];
}
