import Link from 'next/link';
import { pageMetadata } from '@/lib/seo';
import { FOUNDED_YEAR } from '@/constants/app';
// Build-time snapshot of the headline numbers (regenerated by the data
// pipeline alongside the operations JSON, so it can't drift from the map's
// dataset). The map's runtime fetch is versioned with this snapshot's
// generatedAt stamp, so page copy, in-map tiles, and the map's own panel
// all describe the same dataset generation.
import operationsStats from '../../../../public/data/operations_stats.json';
// Build-time import (server-only — nothing here ships to the client): the
// slim operations dataset feeds the cumulative-deployments chart, computed
// once at build. Same pipeline generation as the stats snapshot above.
import operationsData from '../../../../public/data/operations_data.json';
import TrackRecordMap from './TrackRecordMap';

const STATS = {
  deployments: operationsStats.deployments,
  countries: operationsStats.countries,
  years: new Date().getFullYear() - FOUNDED_YEAR,
};

export const metadata = pageMetadata({
  title: 'Track Record',
  description: `Explore Petromac's global deployment history across ${STATS.countries}+ countries with our interactive operations map.`,
  path: '/track-record',
});

/**
 * Records & milestones. Every fact verified against repo content
 * (success-stories PDF text / publications list) — see the strip's
 * source comments. No per-story deep links exist in the flipbook, so
 * cards link to the flipbook (or publications for the SPE paper).
 */
const RECORDS = [
  {
    headline: '80°',
    title: 'World-record gravity descent',
    context:
      'Free descent to 80° deviation in open hole — no tractoring, no pipe. The published record run reached near-horizontal.',
    href: '/success-stories/flipbook',
    cta: 'Success stories',
  },
  {
    headline: '72° in 6" hole',
    title: 'Record slim-hole deviation — Kuwait',
    context:
      'Slim tool taxis carried a triple combo plus pressure testing to a record 72° in a 6" wellbore — no pipe-conveyed logging.',
    href: '/success-stories/flipbook',
    cta: 'Success stories',
  },
  {
    headline: '8 days saved',
    title: 'Pipe-conveyed logging eliminated — Mexico',
    context:
      'Gravity descent with Wireline Express replaced PCL on a deviated well, saving 8 days of rig time.',
    href: '/success-stories/flipbook',
    cta: 'Success stories',
  },
  {
    headline: '$9.4M saved',
    title: 'Deepwater high-angle well — Nam Con Son Basin',
    context: 'Innovative conveyance on a deepwater, high-angle well — published at SPE/ICoTA 2017.',
    href: '/about/publications',
    cta: 'Read the paper',
  },
];

/** Cumulative successful deployments per year, computed at build time. */
function cumulativeByYear() {
  const perYear = new Map<number, number>();
  for (const r of operationsData as { Year: string | number; Successful: string | number }[]) {
    const year = Number(r.Year);
    const successful = Number(r.Successful) || 0;
    if (!Number.isFinite(year) || year < 2000 || successful <= 0) continue;
    perYear.set(year, (perYear.get(year) ?? 0) + successful);
  }
  const years = [...perYear.keys()].sort((a, b) => a - b);
  let running = 0;
  return years.map((year) => {
    running += perYear.get(year) ?? 0;
    return { year, total: running };
  });
}

/** Static inline-SVG area chart — no charting library, fully server-rendered. */
function GrowthChart() {
  const points = cumulativeByYear();
  if (points.length < 2) return null;

  const W = 800;
  const H = 150;
  const PAD = { top: 14, right: 16, bottom: 22, left: 16 };
  const minYear = points[0].year;
  const maxYear = points[points.length - 1].year;
  const maxTotal = points[points.length - 1].total;

  const x = (year: number) =>
    PAD.left + ((year - minYear) / (maxYear - minYear)) * (W - PAD.left - PAD.right);
  const y = (total: number) => PAD.top + (1 - total / maxTotal) * (H - PAD.top - PAD.bottom);

  const line = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${x(p.year)},${y(p.total)}`).join(' ');
  const area = `${line} L${x(maxYear)},${H - PAD.bottom} L${x(minYear)},${H - PAD.bottom} Z`;
  const last = points[points.length - 1];

  return (
    <figure aria-label={`Cumulative successful deployments, ${minYear} to ${maxYear}`}>
      <svg
        viewBox={`0 0 ${W} ${H}`}
        className="w-full h-auto"
        role="img"
        aria-hidden="true"
        focusable="false"
      >
        <path d={area} fill="#1E4A9A" fillOpacity="0.08" />
        <path d={line} fill="none" stroke="#1E4A9A" strokeWidth="2.5" strokeLinejoin="round" />
        <circle cx={x(last.year)} cy={y(last.total)} r="4" fill="#1E4A9A" />
        <text x={PAD.left} y={H - 6} fontSize="11" fill="#64748b">
          {minYear}
        </text>
        <text x={W - PAD.right} y={H - 6} fontSize="11" fill="#64748b" textAnchor="end">
          {maxYear}
        </text>
        <text
          x={x(last.year) - 10}
          y={y(last.total) + 4}
          fontSize="12"
          fontWeight="700"
          fill="#1E4A9A"
          textAnchor="end"
        >
          {last.total.toLocaleString()}
        </text>
      </svg>
      <figcaption className="mt-1 text-xs uppercase tracking-[0.18em] text-slate-500">
        Cumulative successful deployments
      </figcaption>
    </figure>
  );
}

/**
 * Server component: the map is the page hero. Header carries the headline
 * numbers in one crawlable sentence; the three stats also overlay the map
 * card as compact tiles (server-rendered, pointer-transparent). Below the
 * map: build-time growth chart and the verified records strip with the
 * relocated Success Stories CTA.
 */
export default function TrackRecordPage() {
  return (
    <div className="bg-slate-50">
      {/* 1. Compact header — H1 + one sentence that doubles as the
             crawler-visible summary. */}
      <section className="container mx-auto px-4 pt-8 pb-5">
        <h1 className="font-heading text-3xl md:text-4xl font-bold text-slate-900 tracking-tight">
          Track record
        </h1>
        <p className="mt-2 text-slate-600 max-w-3xl">
          {STATS.deployments.toLocaleString()}+ successful wireline deployments across{' '}
          {STATS.countries} countries over {STATS.years}+ years — every job mapped below, filterable
          by system.
        </p>
      </section>

      {/* 2. Map hero — full width, partially above the fold at 1440×900.
             `isolate` fences the card's internal z-indexes (legend, panels,
             tooltip) into their own stacking context so they can never
             paint over the sticky site header. */}
      <section className="bg-slate-900 pt-5 md:pt-6 pb-10 md:pb-14">
        <div className="px-3 md:px-6 lg:px-10">
          <div className="relative isolate w-full rounded-2xl overflow-hidden bg-white shadow-2xl ring-1 ring-slate-200">
            {/* Stat tiles — server-rendered inside the map card, styled to
                match the in-map overlay cards (legend top-right). Desktop:
                stacked top-left, pointer-transparent so they never block
                map interaction. Mobile: slim row above the map. */}
            <div
              className="
                grid grid-cols-3 gap-2 p-3 border-b border-slate-100
                md:grid-cols-1 md:gap-2 md:p-0 md:border-0
                md:absolute md:top-4 md:left-4 md:z-40 md:w-[132px]
                md:pointer-events-none
              "
            >
              <StatTile value={STATS.deployments} suffix="+" label="Deployments" />
              <StatTile value={STATS.countries} label="Countries" />
              <StatTile value={STATS.years} suffix="+" label="Years" />
            </div>
            <TrackRecordMap stats={STATS} dataVersion={operationsStats.generatedAt} />
          </div>
        </div>
      </section>

      {/* 3½. Growth over time — computed at build, zero client JS. */}
      <section className="container mx-auto px-4 pt-10 md:pt-12">
        <div className="rounded-2xl bg-white ring-1 ring-slate-200 shadow-card px-5 py-4 md:px-8 md:py-6">
          <GrowthChart />
        </div>
      </section>

      {/* 3. Records & milestones — verified facts, server-rendered. */}
      <section className="container mx-auto px-4 py-10 md:py-14">
        <h2 className="font-heading text-2xl md:text-3xl font-bold text-slate-900 mb-6">
          Records &amp; milestones
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">
          {RECORDS.map((record) => (
            <Link
              key={record.title}
              href={record.href}
              className="group flex flex-col rounded-xl bg-white ring-1 ring-slate-200 shadow-card p-5 hover:ring-brand/40 hover:shadow-lg transition-all"
            >
              <p className="font-heading text-3xl font-bold text-brand tabular-nums">
                {record.headline}
              </p>
              <p className="mt-1.5 font-semibold text-slate-900 text-sm">{record.title}</p>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed flex-1">{record.context}</p>
              <p className="mt-3 text-sm font-semibold text-brand">
                {record.cta}{' '}
                <span
                  aria-hidden="true"
                  className="inline-block transition-transform group-hover:translate-x-0.5"
                >
                  →
                </span>
              </p>
            </Link>
          ))}
        </div>

        {/* Relocated CTA (was a floating button at the top of the page) */}
        <div className="mt-8 flex justify-center">
          <Link
            href="/success-stories/flipbook"
            className="
              inline-flex items-center gap-2 whitespace-nowrap
              px-7 py-3 rounded-full font-semibold text-white
              bg-brand hover:bg-brand/90 shadow-lg shadow-blue-900/20
              ring-1 ring-blue-900/10
              transition-all hover:translate-y-[-1px] hover:shadow-xl
              focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
            "
          >
            <span>Read the Success Stories</span>
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2.5}
                d="M9 5l7 7-7 7"
              />
            </svg>
          </Link>
        </div>
      </section>
    </div>
  );
}

/** Compact stat tile matching the map's overlay-card styling. */
function StatTile({
  value,
  label,
  suffix = '',
}: {
  value: number;
  label: string;
  suffix?: string;
}) {
  return (
    <div className="bg-white/95 backdrop-blur-md border border-slate-200 rounded-lg shadow px-3 py-2">
      <p className="text-lg font-bold text-brand tabular-nums leading-none">
        {value.toLocaleString()}
        {suffix}
      </p>
      <p className="mt-1 text-[10px] uppercase tracking-[0.2em] text-slate-500">{label}</p>
    </div>
  );
}
