import Link from 'next/link';
import { pageMetadata } from '@/lib/seo';
import { FOUNDED_YEAR } from '@/constants/app';
// Build-time snapshot of the headline numbers (regenerated by the data
// pipeline alongside the operations JSON, so it can't drift from the map's
// dataset). Importing it here means the stat tiles are real numbers in the
// server-rendered HTML — crawlers never see empty labels.
import operationsStats from '../../../../public/data/operations_stats.json';
import TrackRecordMap from './TrackRecordMap';

const STATS = {
  deployments: operationsStats.deployments,
  countries: operationsStats.countries,
  years: new Date().getFullYear() - FOUNDED_YEAR,
};

export const metadata = pageMetadata({
  title: 'Track Record',
  description: `Explore Petromac's global deployment history across ${STATS.countries}+ countries with our interactive operations map.`,
  path: '/track-record',
});

/**
 * Server component: header, stat tiles, and page chrome are all in the
 * initial HTML. Only the interactive map (TrackRecordMap) is a client
 * island — it fetches the full operations dataset after mount.
 */
export default function TrackRecordPage() {
  return (
    <div className="bg-slate-50">
      {/* Header band — compact: the visible headline was dropped so the map
          sits higher on first open; an sr-only h1 keeps the page's heading
          semantics for SEO and screen readers. */}
      <section className="container mx-auto px-4 pt-6 pb-4">
        <h1 className="sr-only">Track Record</h1>
        <div className="flex justify-end">
          <Link
            href="/success-stories/flipbook"
            className="
              self-start md:self-end inline-flex items-center gap-2 whitespace-nowrap
              px-6 py-3 rounded-full font-semibold text-white
              bg-brand hover:bg-brand/90 shadow-lg shadow-blue-900/20
              ring-1 ring-blue-900/10
              transition-all hover:translate-y-[-1px] hover:shadow-xl
              focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
            "
          >
            <span>Read the Success Stories</span>
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2.5}
                d="M9 5l7 7-7 7"
              />
            </svg>
          </Link>
        </div>
      </section>

      {/* Hero stats — 3 compact tiles; kept small so the map is visible
          on first open without scrolling. */}
      <section className="container mx-auto px-4 pb-6">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 md:gap-4">
          <StatTile label="Deployments" value={STATS.deployments} suffix="+" />
          <StatTile label="Countries" value={STATS.countries} suffix="+" />
          <StatTile label="Years of operations" value={STATS.years} suffix="+" />
        </div>
      </section>

      {/* Map — full bleed on large screens with a deep brand frame */}
      <section className="bg-slate-900 pt-6 md:pt-10 pb-12 md:pb-16">
        <div className="px-3 md:px-6 lg:px-10">
          <div className="relative w-full rounded-2xl overflow-hidden bg-white shadow-2xl ring-1 ring-slate-200">
            <TrackRecordMap stats={STATS} />
          </div>
        </div>
      </section>
    </div>
  );
}

function StatTile({
  label,
  value,
  suffix = '',
}: {
  label: string;
  value: number;
  suffix?: string;
}) {
  return (
    <div className="rounded-xl bg-white border border-slate-200 shadow-sm px-5 py-4 md:py-5 text-center">
      <p className="font-heading text-3xl md:text-4xl font-bold text-brand tabular-nums leading-none">
        {value.toLocaleString()}
        {suffix}
      </p>
      <p className="mt-2 text-xs uppercase tracking-[0.18em] text-slate-500 font-medium">{label}</p>
    </div>
  );
}
